// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVGbSi7ID6bmK9nvP0yEtHixr4VN0sXao',
    appId: '1:353628628419:web:a3a975c6f1d1e641e30976',
    messagingSenderId: '353628628419',
    projectId: 'gestion-depense-56916',
    authDomain: 'gestion-depense-56916.firebaseapp.com',
    storageBucket: 'gestion-depense-56916.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBUOXDuwWhmwACMBPhJsrm-KmUihwenQw',
    appId: '1:353628628419:android:595da5a8fb02444be30976',
    messagingSenderId: '353628628419',
    projectId: 'gestion-depense-56916',
    storageBucket: 'gestion-depense-56916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVHxh3gquQIvVhSYFhKr72ytpD3NMIyYU',
    appId: '1:353628628419:ios:c389a0161fde19fde30976',
    messagingSenderId: '353628628419',
    projectId: 'gestion-depense-56916',
    storageBucket: 'gestion-depense-56916.firebasestorage.app',
    iosBundleId: 'com.example.gestionDepense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVHxh3gquQIvVhSYFhKr72ytpD3NMIyYU',
    appId: '1:353628628419:ios:c389a0161fde19fde30976',
    messagingSenderId: '353628628419',
    projectId: 'gestion-depense-56916',
    storageBucket: 'gestion-depense-56916.firebasestorage.app',
    iosBundleId: 'com.example.gestionDepense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVGbSi7ID6bmK9nvP0yEtHixr4VN0sXao',
    appId: '1:353628628419:web:697312301fd99f06e30976',
    messagingSenderId: '353628628419',
    projectId: 'gestion-depense-56916',
    authDomain: 'gestion-depense-56916.firebaseapp.com',
    storageBucket: 'gestion-depense-56916.firebasestorage.app',
  );

}